# SOME DESCRIPTIVE TITLE.
# Copyright (C) Zoomer Analytics LLC
# This file is distributed under the same license as the xlwings package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2020.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: xlwings dev\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-04-06 16:16+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"

#: ../../troubleshooting.rst:4
msgid "Troubleshooting"
msgstr "トラブルシューティング"

#: ../../troubleshooting.rst:7
msgid "Issue: dll not found"
msgstr "問題: dllが見つかりません"

#: ../../troubleshooting.rst:9
msgid "Solution:"
msgstr "解決方:"

#: ../../troubleshooting.rst:11
msgid ""
"``xlwings32-<version>.dll`` and ``xlwings64-<version>.dll`` are both in "
"the same directory as your ``python.exe``. If not, something went wrong "
"with your installation. Reinstall it with ``pip`` or ``conda``, see "
":ref:`installation`."
msgstr ""
"``xlwings32-<version>.dll`` と ``xlwings64-<version>.dll`` は両方とも "
"``python.exe`` と同じディレクトリーにあります。もし無ければ、インストールに"
"問題が生じています。 ``pip`` か ``conda`` で再インストールしてください。 "
":ref:`installation` を参照してください。"

#: ../../troubleshooting.rst:13
msgid ""
"Check your ``Interpreter`` in the add-in or config sheet. If it is empty,"
" then you need to be able to open a windows command prompt and type "
"``python`` to start an interactive Python session. If you get the error "
"``'python' is not recognized as an internal or external command, operable"
" program or batch file.``, then you have two options: Either add the path"
" of where your ``python.exe`` lives to your Windows path (see "
"https://www.computerhope.com/issues/ch000549.htm) or set the full path to"
" your interpreter in the add-in or your config sheet, e.g. "
"``C:\\Users\\MyUser\\anaconda\\pythonw.exe``"
msgstr ""
"アドインまたは設定シートの ``Interpreter`` を確認してください。"
"空白の場合、Windowsのコマンド プロンプトで ``python`` と入力して"
"Pythonの対話モードが開始できなければなりません。"
"``'python' は、内部コマンドまたは外部コマンド、操作可能なプログラムまたは"
"バッチ ファイルとして認識されていません。`` と表示されたら、次のいずれかを"
"試してみてください: ``python.exe`` があるフォルダーをWindows パスに"
"追加(参照 "https://www.computerhope.com/issues/ch000549.htm)、"
"または、アドインまたは設定シートに ``python.exe`` のフルパスを設定"
"（例 ``C:\\Users\\MyUser\\anaconda\\pythonw.exe`` ）"

